### ISSUE TITLE
List of all courses that are only in the 'Fall 2018' term?

### ISSUE THREAD

**Issue by jvriccione** [Purdue-io/PurdueApi#25]
How do I get a list of all courses that are only in the 'Fall 2018' term ordered by Subject/Abbreviation?

**Comment by haydenmc** [comment]
Hey there, I think this is the query you're looking for:

[https://api.purdue.io/odata/Courses/?$filter=(Classes/any(c: c/Term/TermCode eq '201910'))&$orderby=Subject/Abbreviation asc, Number asc](https://api.purdue.io/odata/Courses/?$filter=(Classes/any(c:%20c/Term/TermCode%20eq%20'201910'))&$orderby=Subject/Abbreviation%20asc,%20Number%20asc)

This will return a list of every course with a class that has a term with `TermCode` equal to `201910` (Fall 2018), ordered first by Subject/Abbreviation, then by Course Number.

Hope that helps! Let me know if you need any more details.
