### ISSUE TITLE
CatalogSync incorrectly handles username CLI option

### ISSUE THREAD

**Issue by spanglel** [Purdue-io/PurdueApi#51]
Line 61 of src/PurdueApi/Program.cs currently reads:
```cs
string username = options.MyPurduePass ?? 
    Environment.GetEnvironmentVariable("MY_PURDUE_USERNAME");
```
This incorrectly sends the password as the username if the command line options were used rather than environment variables. The line should read:
```cs
string username = options.MyPurdueUser ?? 
    Environment.GetEnvironmentVariable("MY_PURDUE_USERNAME");
```

**Comment by haydenmc** [comment]
Thanks for the report! Looks like an easy fix - will get a PR out shortly.
